"""Combined (simultaneous) field-distortion robustness (TDD, red first).

Every prior robustness item isolates ONE axis — additive noise (``robustness``),
nonlinear clipping (``clipping_robustness``), convolutive reverb
(``reverb_robustness``), linear level (``gain_robustness``). Real capture stacks
all of them at once. This composes them in the physical signal-chain order a mic
actually sees — **gain -> reverb -> noise -> clip** — and quantifies the
*compounding gap*: how far simultaneous distortion drops accuracy below what the
single-axis sweeps would predict.

Like its siblings the module under test (``model/combined_distortion.py``) is two
layers: a **pure reduction** (``combined_distortion``) unit-tested with hand-set
numbers, and a heavy ``build_combined_distortion`` that trains one tiny net and
evaluates field-distorted eval sets. Host-only; no device, no AI Hub token.

Red-first contract notes (the module does not exist yet — these tests MUST fail
on the missing import/symbols):
  * Per the design brief the ``CombinedDistortionResult`` / ``ProfilePoint`` /
    ``FieldProfile`` helpers are **methods** (``def clean_accuracy(self)`` …),
    *not* ``@property`` as the siblings happen to use. They are called with ``()``
    throughout this file deliberately.
  * The clip stage replicates ``model/clipping_robustness.py``'s ``_clip_wave``
    (hard-clip to ``clip_ratio*peak`` then rescale back to the original peak), so
    the order test reproduces that exact logic.
  * The build's per-``eval_seed`` eval set is generated by
    ``torch.Generator().manual_seed(eval_seed)`` iterating
    ``for stressed in (False, True): for _ in range(eval_n_per_class)`` via
    ``model.data._synth_waveform`` — the convention the clean-baseline check below
    reproduces.
"""

from __future__ import annotations

import json

import pytest

BAR = 0.8


def _rec(name, gain_db, rt60_s, snr_db, clip_ratio, accuracy, acc_std=None, n=64):
    """Build one (name, gain_db, rt60_s, snr_db, clip_ratio, acc, acc_std, n) record."""
    return (name, gain_db, rt60_s, snr_db, clip_ratio, accuracy, acc_std, n)


# --- injector: apply_field_profile (composes the signal chain) --------------

def test_clean_profile_is_identity_and_draws_no_rng():
    """crit 3a (injector level): a clean/identity profile returns the wave
    bit-for-bit and consumes no RNG, so it reproduces clean features exactly."""
    import torch

    from model.combined_distortion import DEFAULT_PROFILES, apply_field_profile
    from model.data import _synth_waveform

    profiles = {p.name: p for p in DEFAULT_PROFILES}
    wave = _synth_waveform(False, torch.Generator().manual_seed(0))

    gen = torch.Generator().manual_seed(123)
    state_before = gen.get_state()
    out, diag = apply_field_profile(wave, profiles["clean"], gen)
    state_after = gen.get_state()

    assert torch.equal(out, wave)                 # bit-for-bit unchanged
    assert torch.equal(state_before, state_after)  # no RNG draw
    assert diag["tail_fraction"] == 0.0
    assert diag["clipped_fraction"] == 0.0


def test_perturbation_magnitude_is_monotone():
    """Harsher profiles perturb the waveform more: L2 from clean is
    harsh > typical > quiet > clean == 0."""
    import torch

    from model.combined_distortion import DEFAULT_PROFILES, apply_field_profile
    from model.data import _synth_waveform

    profiles = {p.name: p for p in DEFAULT_PROFILES}
    wave = _synth_waveform(False, torch.Generator().manual_seed(0))

    def dist(name):
        gen = torch.Generator().manual_seed(7)
        out, _ = apply_field_profile(wave, profiles[name], gen)
        return float((out - wave).pow(2).sum().sqrt())

    d_clean = dist("clean")
    d_quiet = dist("quiet")
    d_typical = dist("typical")
    d_harsh = dist("harsh")

    assert d_clean == 0.0
    assert d_harsh > d_typical > d_quiet > d_clean


def test_noise_present_iff_snr_set():
    """Noise is added exactly when ``snr_db`` is set. Holding gain fixed and
    flipping only ``snr_db`` isolates the noise stage."""
    import torch

    from model.combined_distortion import FieldProfile, apply_field_profile
    from model.data import _synth_waveform

    wave = _synth_waveform(False, torch.Generator().manual_seed(0))
    factor = 10.0 ** (-6.0 / 20.0)

    prof_gain = FieldProfile("g", -6.0, 0.0, None, 1.0)      # gain only, no noise
    prof_noisy = FieldProfile("gn", -6.0, 0.0, 10.0, 1.0)    # gain + noise

    out_gain, _ = apply_field_profile(wave, prof_gain, torch.Generator().manual_seed(0))
    out_noisy, _ = apply_field_profile(wave, prof_noisy, torch.Generator().manual_seed(0))

    # snr_db is None -> deterministic gain only, no additive noise
    assert torch.allclose(out_gain, wave * factor, atol=1e-6)
    # snr_db set -> noise present, so it differs from the noise-free gain output
    assert not torch.allclose(out_noisy, out_gain, atol=1e-6)


def test_reverb_is_length_preserved():
    """Reverb smears the envelope but keeps the signal length, and reports a
    non-zero reverberant tail."""
    import torch

    from model.combined_distortion import FieldProfile, apply_field_profile
    from model.data import _synth_waveform

    wave = _synth_waveform(False, torch.Generator().manual_seed(0))
    prof_rev = FieldProfile("r", 0.0, 0.3, None, 1.0)        # reverb only

    out, diag = apply_field_profile(wave, prof_rev, torch.Generator().manual_seed(0))

    assert out.shape == wave.shape
    assert not torch.allclose(out, wave, atol=1e-6)
    assert diag["tail_fraction"] > 0.0


def test_clip_applied_last_after_noise():
    """Clipping is the LAST stage: the output equals noise-then-clip of the
    input (clip replicates ``_clip_wave``: clamp to ``ratio*peak``, rescale to
    the post-noise peak). Reproducing the chain by hand pins the order."""
    import torch

    from model.combined_distortion import FieldProfile, apply_field_profile
    from model.data import _synth_waveform
    from model.robustness import _add_noise

    wave = _synth_waveform(False, torch.Generator().manual_seed(0))
    prof = FieldProfile("nc", 0.0, 0.0, 10.0, 0.5)           # noise then clip

    out, diag = apply_field_profile(wave, prof, torch.Generator().manual_seed(123))

    # Reproduce the documented chain: gain 0 dB (identity) -> rt60 0 (identity)
    # -> noise at the same seeded draw -> hard-clip rescaled to the post-noise peak.
    noisy = _add_noise(wave, 10.0, torch.Generator().manual_seed(123), color="white")
    peak = noisy.abs().max()
    thr = 0.5 * peak
    expected = noisy.clamp(-thr, thr) * (peak / thr)

    assert torch.allclose(out, expected, atol=1e-5)
    assert diag["clipped_fraction"] > 0.0


def test_fieldprofile_is_clean_and_default_profiles():
    """``is_clean`` is true only when every axis is degenerate; the five named
    DEFAULT_PROFILES are present with only ``clean`` degenerate."""
    from model.combined_distortion import DEFAULT_PROFILES, FieldProfile

    profiles = {p.name: p for p in DEFAULT_PROFILES}
    assert set(profiles) == {"clean", "quiet", "typical", "harsh", "worst_case"}

    assert profiles["clean"].is_clean() is True
    for nm in ("quiet", "typical", "harsh", "worst_case"):
        assert profiles[nm].is_clean() is False

    assert FieldProfile("x", 0.0, 0.0, None, 1.0).is_clean() is True
    assert FieldProfile("x", 0.0, 0.0, None, 0.9).is_clean() is False   # clip < 1
    assert FieldProfile("x", -3.0, 0.0, None, 1.0).is_clean() is False  # gain
    assert FieldProfile("x", 0.0, 0.2, None, 1.0).is_clean() is False   # reverb
    assert FieldProfile("x", 0.0, 0.0, 20.0, 1.0).is_clean() is False   # noise


# --- pure reduction (hand-set numbers, no training) -------------------------

def test_reduction_clean_and_worst_accuracy():
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.95),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.88),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.70),
    ]
    single = {"typical": 0.92, "harsh": 0.80}
    out = combined_distortion(records, single_axis=single, accuracy_bar=BAR, out_dir=None)

    assert out.clean_accuracy() == pytest.approx(0.95)
    assert out.worst_accuracy() == pytest.approx(0.70)
    assert set(out.reliable_profiles()) == {"clean", "typical"}


def test_profilepoint_compounding_gap_and_reliable():
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.95),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.88),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.70),
    ]
    single = {"typical": 0.92, "harsh": 0.80}
    out = combined_distortion(records, single_axis=single, accuracy_bar=BAR, out_dir=None)
    by = {p.name: p for p in out.points}

    assert by["typical"].compounding_gap() == pytest.approx(0.04)
    assert by["harsh"].compounding_gap() == pytest.approx(0.10)
    assert by["clean"].compounding_gap() is None          # no matched single axis
    assert out.max_compounding_gap() == pytest.approx(0.10)

    assert by["clean"].reliable(BAR) is True
    assert by["harsh"].reliable(BAR) is False


def test_graceful_true_verdict():
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.95),
        _rec("quiet", -3.0, 0.15, 20.0, 0.9, 0.90),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.85),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.82),
    ]
    out = combined_distortion(records, accuracy_bar=BAR, out_dir=None)

    assert out.graceful() is True
    assert "graceful" in out.verdict().lower()


def test_negative_gap_anomaly_is_flagged():
    """A profile that scores ABOVE its matched single-axis baseline (negative
    compounding gap) is physically impossible as real robustness — it must be
    surfaced as an anomaly and the verdict must carry the synthetic-eval caveat,
    even when every profile clears the bar (graceful)."""
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.96),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.90),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.88),
        _rec("worst_case", -12.0, 1.0, -5.0, 0.25, 0.98),  # beats its baseline
    ]
    single = {"typical": 0.92, "harsh": 0.95, "worst_case": 0.82}
    out = combined_distortion(records, single_axis=single, accuracy_bar=BAR, out_dir=None)

    assert out.graceful() is True                       # every profile clears the bar
    assert out.anomalous_profiles() == ("worst_case",)  # the -0.16 gap profile
    v = out.verdict().lower()
    assert "graceful" in v                              # base verdict preserved
    assert "caveat" in v and "synthetic" in v          # honesty caveat appended
    assert "worst_case" in out.verdict()
    # a clean (no single_axis) result has no anomaly and no caveat
    clean_only = combined_distortion(records, accuracy_bar=BAR, out_dir=None)
    assert clean_only.anomalous_profiles() == ()
    assert "caveat" not in clean_only.verdict().lower()


def test_graceful_false_verdict_names_compounding():
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.95),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.88),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.70),
    ]
    single = {"typical": 0.92, "harsh": 0.85}
    out = combined_distortion(records, single_axis=single, accuracy_bar=BAR, out_dir=None)

    assert out.graceful() is False
    # clean clears the bar but harsh falls below -> compounding-degradation verdict
    assert "compounding" in out.verdict().lower()


def test_compounding_gap_nonnegative_property():
    """crit 3c, encoded as a property of the REDUCTION (not the trained model):
    when each profile's accuracy <= its matched single-axis accuracy, every
    reported compounding gap is >= 0, and a sub-bar profile names compounding."""
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.96),
        _rec("quiet", -3.0, 0.15, 20.0, 0.9, 0.90),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.82),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.60),
    ]
    single = {"quiet": 0.93, "typical": 0.90, "harsh": 0.75}
    out = combined_distortion(records, single_axis=single, accuracy_bar=BAR, out_dir=None)

    gaps = [p.compounding_gap() for p in out.points if p.compounding_gap() is not None]
    assert gaps                                  # at least the non-clean profiles
    assert all(g >= 0.0 for g in gaps)
    assert out.max_compounding_gap() >= 0.0
    assert "compounding" in out.verdict().lower()


def test_reduction_preserves_monotone_accuracies():
    """crit 3b, as a property of the reduction: a monotone-by-severity input
    keeps its non-increasing accuracy ordering through the reduction."""
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.98),
        _rec("quiet", -3.0, 0.15, 20.0, 0.9, 0.90),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.85),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.80),
    ]
    out = combined_distortion(records, accuracy_bar=BAR, out_dir=None)
    by = {p.name: p for p in out.points}

    assert by["quiet"].accuracy >= by["typical"].accuracy >= by["harsh"].accuracy
    assert len(out.points) == 4


def test_reduction_handles_nonmonotone_records():
    """A non-monotone input still reduces cleanly (no crash, valid verdict)."""
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.95),
        _rec("quiet", -3.0, 0.15, 20.0, 0.9, 0.80),    # dips
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.90),   # rebounds (non-monotone)
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.70),
    ]
    out = combined_distortion(records, accuracy_bar=BAR, out_dir=None)

    assert len(out.points) == 4
    assert isinstance(out.verdict(), str) and len(out.verdict()) > 10
    assert out.worst_accuracy() == pytest.approx(0.70)


def test_to_dict_round_trips_and_byte_stable():
    from model.combined_distortion import combined_distortion

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.95),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.88),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.70),
    ]
    single = {"typical": 0.92, "harsh": 0.80}
    out = combined_distortion(records, single_axis=single, accuracy_bar=BAR, out_dir=None)

    s1 = json.dumps(out.to_dict(), sort_keys=True)
    s2 = json.dumps(out.to_dict(), sort_keys=True)
    assert s1 == s2                              # byte-stable

    back = json.loads(s1)
    assert "accuracy_bar" in back
    assert "verdict" in back
    assert "points" in back and len(back["points"]) == 3
    pt = back["points"][0]
    assert "name" in pt and "accuracy" in pt


def test_to_markdown_contains_names_and_verdict():
    from model.combined_distortion import combined_distortion, to_markdown

    records = [
        _rec("clean", 0.0, 0.0, None, 1.0, 0.95),
        _rec("quiet", -3.0, 0.15, 20.0, 0.9, 0.90),
        _rec("typical", -6.0, 0.3, 10.0, 0.6, 0.85),
        _rec("harsh", -12.0, 0.6, 0.0, 0.35, 0.82),
    ]
    out = combined_distortion(records, accuracy_bar=BAR, out_dir=None)
    md = to_markdown(out)

    for nm in ("clean", "quiet", "typical", "harsh"):
        assert nm in md
    assert out.verdict() in md                   # verdict embedded verbatim


# --- index registration -----------------------------------------------------

def test_registered_in_benchmarks_index():
    from model.benchmarks_index import _ARTIFACTS

    names = [a[0] for a in _ARTIFACTS]
    assert "combined_distortion.json" in names


# --- heavy build path (trains + field-distorts eval sets) -------------------

def test_build_combined_distortion_end_to_end(tmp_path):
    """crit 3a end-to-end: the clean profile is the identity baseline, so its
    accuracy equals the same model's accuracy on the same undistorted eval set
    EXACTLY. The harsh check is a SOFT, flake-resistant sanity guard (the tiny
    2-epoch model is stochastic — no hard strict inequality)."""
    import torch

    from model.combined_distortion import build_combined_distortion
    from model.data import _synth_waveform
    from model.features import extract
    from model.production import train_production

    out = build_combined_distortion(
        seed=0, epochs=2, n_per_class=16, eval_n_per_class=16,
        eval_seeds=(0,), accuracy_bar=BAR, out_dir=tmp_path,
    )

    assert (tmp_path / "combined_distortion.json").is_file()
    assert (tmp_path / "combined_distortion.md").is_file()

    by = {p.name: p for p in out.points}
    assert "clean" in by and "harsh" in by

    # Separately-computed clean baseline: identical model (train_production is
    # deterministic) on the identically-seeded eval set, NO distortion.
    model, _ = train_production(epochs=2, n_per_class=16, seed=0, threshold=0.8)
    model = model.eval()
    feats, labels = [], []
    for eval_seed in (0,):
        gen = torch.Generator().manual_seed(eval_seed)
        for stressed in (False, True):
            for _ in range(16):
                wave = _synth_waveform(stressed, gen)
                feats.append(extract(wave))     # clean profile == identity
                labels.append(float(stressed))
    x = torch.cat(feats, dim=0)
    y = torch.tensor(labels, dtype=torch.float32).unsqueeze(1)
    with torch.no_grad():
        pred = (model(x).flatten() >= 0.5).float()
    baseline = (pred == y.flatten()).float().mean().item()

    assert by["clean"].accuracy == pytest.approx(baseline, abs=1e-6)
    assert out.clean_accuracy() == pytest.approx(baseline, abs=1e-6)

    # SOFT sanity: simultaneous distortion should not make harsh much better
    # than clean (a gross inversion would signal an order/identity bug).
    assert by["harsh"].accuracy <= by["clean"].accuracy + 0.25
